.TH "Codigo" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Codigo \- Classe que representa um co\*(`digo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Codigo\&.hpp>\fP
.PP
Subclasse de \fBDominio\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBCodigo\fP (std::string codigo)"
.br
.RI "Construtor da classe Co\*(`digo\&. "
.ti -1c
.RI "std::string \fBgetCodigo\fP () const"
.br
.RI "Obte\*(`m o co\*(`digo atual\&. "
.ti -1c
.RI "void \fBsetCodigo\fP (std::string novoCodigo)"
.br
.RI "Define um novo co\*(`digo\&. "
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe que representa um co\*(`digo\&. 

Esta classe representa um co\*(`digo, que e\*(` uma seque\*^ncia de caracteres\&. Ela fornece me\*(`todos para obter e definir o co\*(`digo, bem como para validar sua formatac\*,a\*~o\&. 
.PP
Definição na linha \fB15\fP do arquivo \fBCodigo\&.hpp\fP\&.
.SH "Construtores e Destrutores"
.PP 
.SS "Codigo::Codigo (std::string codigo)"

.PP
Construtor da classe Co\*(`digo\&. 
.PP
\fBParâmetros\fP
.RS 4
\fIcodigo\fP A seque\*^ncia de caracteres que representa o co\*(`digo\&. 
.RE
.PP

.PP
Definição na linha \fB5\fP do arquivo \fBCodigo\&.cpp\fP\&.
.SH "Documentação das funções"
.PP 
.SS "std::string Codigo::getCodigo () const"

.PP
Obte\*(`m o co\*(`digo atual\&. 
.PP
\fBRetorna\fP
.RS 4
Uma string representando o co\*(`digo atual\&. 
.RE
.PP

.PP
Definição na linha \fB24\fP do arquivo \fBCodigo\&.cpp\fP\&.
.SS "void Codigo::setCodigo (std::string novoCodigo)"

.PP
Define um novo co\*(`digo\&. 
.PP
\fBParâmetros\fP
.RS 4
\fInovoCodigo\fP O novo co\*(`digo a ser definido\&. 
.RE
.PP

.PP
Definição na linha \fB28\fP do arquivo \fBCodigo\&.cpp\fP\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
