.TH "Coluna" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Coluna \- Classe que representa uma coluna\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Coluna\&.hpp>\fP
.PP
Subclasse de \fBDominio\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBColuna\fP (std::string coluna)"
.br
.ti -1c
.RI "void \fBsetColuna\fP (std::string novaColuna)"
.br
.RI "Define uma nova coluna\&. "
.ti -1c
.RI "std::string \fBgetColuna\fP () const"
.br
.RI "Obte\*(`m a coluna atual\&. "
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe que representa uma coluna\&. 

Esta classe representa uma coluna, que pode ser validada de acordo com algum crite\*(`rio definido\&. 
.PP
Definição na linha \fB13\fP do arquivo \fBColuna\&.hpp\fP\&.
.SH "Construtores e Destrutores"
.PP 
.SS "Coluna::Coluna (std::string coluna)"

.PP
Definição na linha \fB4\fP do arquivo \fBColuna\&.cpp\fP\&.
.SH "Documentação das funções"
.PP 
.SS "std::string Coluna::getColuna () const"

.PP
Obte\*(`m a coluna atual\&. 
.PP
\fBRetorna\fP
.RS 4
Uma string representando a coluna atual\&. 
.RE
.PP

.PP
Definição na linha \fB21\fP do arquivo \fBColuna\&.cpp\fP\&.
.SS "void Coluna::setColuna (std::string novaColuna)"

.PP
Define uma nova coluna\&. 
.PP
\fBParâmetros\fP
.RS 4
\fInovaColuna\fP A nova seque\*^ncia de caracteres a ser definida como coluna\&. 
.RE
.PP

.PP
Definição na linha \fB25\fP do arquivo \fBColuna\&.cpp\fP\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
