.TH "C:/Users/danie/unb_local/trabalho-tp1/src/entities/Conta.hpp" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/danie/unb_local/trabalho-tp1/src/entities/Conta.hpp \- Classe que representa uma conta de usua\*(`rio\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include '\&.\&./domains/Email\&.hpp'\fP
.br
\fC#include '\&.\&./domains/Senha\&.hpp'\fP
.br
\fC#include '\&.\&./domains/Texto\&.hpp'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBConta\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Classe que representa uma conta de usua\*(`rio\&. 

Esta classe representa uma conta de usua\*(`rio que conte\*(`m informac\*,o\*~es como email, nome e senha\&. 
.PP
Definição no arquivo \fBConta\&.hpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
