.TH "C:/Users/danie/unb_local/trabalho-tp1/src/domains/Dominio.hpp" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/danie/unb_local/trabalho-tp1/src/domains/Dominio.hpp \- Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBDominio\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <regex>\fP
.br
\fC#include <string>\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBDominio\fP"
.br
.RI "Classe abstrata que representa um domi\*(`nio\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBDominio\fP\&. 


.PP
Definição no arquivo \fBDominio\&.hpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
