.TH "C:/Users/danie/unb_local/trabalho-tp1/src/domains/Limite.hpp" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/danie/unb_local/trabalho-tp1/src/domains/Limite.hpp \- Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBLimite\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&./Dominio\&.hpp'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBLimite\fP"
.br
.RI "Classe que representa um limite\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBLimite\fP\&. 


.PP
Definição no arquivo \fBLimite\&.hpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
