.TH "C:/Users/danie/unb_local/trabalho-tp1/src/entities/Quadro.hpp" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/danie/unb_local/trabalho-tp1/src/entities/Quadro.hpp \- Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBQuadro\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include '\&.\&./domains/Texto\&.hpp'\fP
.br
\fC#include '\&.\&./domains/Codigo\&.hpp'\fP
.br
\fC#include '\&.\&./domains/Limite\&.hpp'\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBQuadro\fP"
.br
.RI "Classe que representa um quadro\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBQuadro\fP\&. 


.PP
Definição no arquivo \fBQuadro\&.hpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
