.TH "C:/Users/danie/unb_local/trabalho-tp1/src/domains/Senha.hpp" 3 "trabalho-tp1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/danie/unb_local/trabalho-tp1/src/domains/Senha.hpp \- Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBSenha\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include '\&./Dominio\&.hpp'\fP
.br
\fC#include <string>\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBSenha\fP"
.br
.RI "Classe que representa uma senha\&. "
.in -1c
.SH "Descrição detalhada"
.PP 
Este arquivo conte\*(`m a declarac\*,a\*~o da classe \fBSenha\fP\&. 


.PP
Definição no arquivo \fBSenha\&.hpp\fP\&.
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para trabalho-tp1 a partir do código fonte\&.
